---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp -R /repositories/ecofoot-gl/application $DEPLOYPATH
    - /bin/cp -R /repositories/ecofoot-gl/css $DEPLOYPATH
    - /bin/cp -R /repositories/ecofoot-gl/fontawesome $DEPLOYPATH
    - /bin/cp -R /repositories/ecofoot-gl/fonts $DEPLOYPATH
    - /bin/cp -R /repositories/ecofoot-gl/images $DEPLOYPATH
    - /bin/cp -R /repositories/ecofoot-gl/img $DEPLOYPATH
    - /bin/cp -R /repositories/ecofoot-gl/js $DEPLOYPATH
    - /bin/cp -R /repositories/ecofoot-gl/media $DEPLOYPATH
    - /bin/cp -R /repositories/ecofoot-gl/pages $DEPLOYPATH
    - /bin/cp -R /repositories/ecofoot-gl/system $DEPLOYPATH
    - /bin/cp -R /repositories/ecofoot-gl/vendor $DEPLOYPATH
    - /bin/cp -R /repositories/ecofoot-gl/video $DEPLOYPATH
    